### ISSUE TITLE
OnsenUIのタブバーについてまとめる

### ISSUE THREAD

**Issue by Rebirthble** [ffa500/ffa500.github.io#26]
- タブバーの実装方法
- ページ遷移の方法

**Comment by Oktasuke** [comment]
タイマーのデモアプリははタブバーで作ってますよー
iOSプリインの「時計」を丸パクリしてます

**Comment by Rebirthble** [comment]
記事をいくつかに分けて書いてもらう形になりそうですね

**Comment by Rebirthble** [comment]
この前のミーティングで改善案が出たと思うので、それを追記したらクローズしていきましょう
