### ISSUE TITLE
Cordovaについてまとめてみる

### ISSUE THREAD

**Issue by Rebirthble** [ffa500/ffa500.github.io#5]

**Comment by hounenhounen** [comment]
## Cordovaとは？

PhoneGapというHTMLとJavaScriptによるハイブリットアプリケーション制作フレームワークがあるそうです。そのオープンソースの名前を「Cordova」というようです。
PhoneGapはもともとNitobi社が開発していたがAdobe社が買収し開発を続けていました。そのごAdobe社がApache Foundationへ寄贈し、Apacheのブランド名として「Cordova」と名付けられたようです。

製品版が「PhoneGap」オープンソース版が「Cordova」。

参考文献：
　http://phonegap-fan.com/about/
　http://furoshiki.hatenadiary.jp/entry/2014/07/23/084643

**Comment by Rebirthble** [comment]
最終的にブログにしてくれるんですよね。。。？

**Comment by Rebirthble** [comment]
http://ffa500.github.io/2015/07/07/about-this-blog.html

**Comment by hounenhounen** [comment]
するつもりですが、このgithub.ioとかを初めて使うので色々使ってみようとしています

**Comment by Rebirthble** [comment]
作成ありがとうございましたー
